
DECLARE @CUSTOMERID AS INT;
DECLARE @ITEMID AS INT;
DECLARE @UNITPRICE AS FLOAT;


SELECT TOP 1 @CUSTOMERID = ID
FROM --TABLE_CUSTOMERS
ORDER BY NEWID();
SELECT TOP 1 @ITEMID = ID, @UNITPRICE = UNITPRICE
FROM --TABLE_ITEMS
ORDER BY NEWID();

SELECT @CUSTOMERID, @ITEMID, @UNITPRICE

DECLARE @DATE AS DATETIME;
DECLARE @RAND AS INT;
DECLARE @AMOUNT AS INT;
DECLARE @LINETOTAL AS FLOAT;

SET @RAND = RAND() * 365;
SET @DATE = DATEADD(DAY, @RAND, 'date');
SET @DATE = DATEADD(HH, 8, @DATE);
SET @RAND = RAND() * 12 * 60 * 60;
SET @DATE = DATEADD(SECOND, @RAND, @DATE);
SET @AMOUNT = 1 + RAND() * 20;
SET @LINETOTAL = @AMOUNT * @UNITPRICE;

INSERT INTO --TABLE_SALES
    (CUSTOMERID, ITEMID, DATE_, AMOUNT, UNITPRICE, LINETOTAL)
VALUES (@CUSTOMERID, @ITEMID, @DATE, @AMOUNT, @UNITPRICE, @LINETOTAL);

SELECT C.NAMESURNAME, I.ITEMNAME, S.*
FROM --TABLE_SALES S
         JOIN --TABLE_ITEMS I ON I.ID = S.ITEMID
         JOIN --TABLE_CUSTOMERS C ON C.ID = S.CUSTOMERID;
